# Part-III solution
version: '3'
volumes:
    prometheus_data: {}
networks:
  front-tier:
  back-tier:
services:

  prometheus:
    image: prom/prometheus:v2.22.0
    volumes:
      - /root/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - csvapp:csvapp
    depends_on:
      - csvapp
    networks:
      - back-tier
    restart: always
  csvapp:
    image: infracloudio/csvserver:latest
    ports:
      - 9393:9300
    volumes:
      - /root/csv_asg/inputFile:/csvserver/inputdata
    environment:
      - CSVSERVER_BORDER=Orange
    networks:
      - back-tier    
    restart: always