# Part-III solution
ersion: '3'
volumes:
   prometheus-data:
networks:
  front-tier:
  back-tier:

services:
  prometheus:
    image: prom/prometheus:v2.22.0
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    links:
      - csvapp:csvapp
    depends_on:
      - csvapp
    networks:
      - back-tier
  csvapp:
    image: infracloudio/csvserver:latest
    ports:
      - 9393:9300
    volumes:
      - /root/csv_asg/inputFile:/csvserver/inputdata
    environment:
      - CSVSERVER_BORDER=Orange
    networks:
      - back-tier    
    restart: always