global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yaml

scrape_configs:
  - job_name: csvapp
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'csvapp:9300'
          - 'idonotexists:564'